import sys, os
import argparse

sys.path.append('/Users/jingyuluo/Downloads/root_dir/lib')

import ROOT

from ROOT import TFile, TCanvas, TH1F
from ROOT import gStyle
from ROOT import kGreen, kRed, kBlue, kBlack

gStyle.SetOptStat(ROOT.kFALSE)
parser=argparse.ArgumentParser()

parser.add_argument("-d1", "--data1", default="test_Run2022C_trigger.root", help="The rootfile for 2022 data") 
parser.add_argument("-d2", "--data2", default="DisplacedJets_Run2018All_Trigger.root", help="The rootfile for 2018 data")
parser.add_argument("-m", "--mc", default="Trigger_OffSel_QCD_HT_Merged_New_92X.root", help="The rootfile for Run2 MC")

args = parser.parse_args()

dataname = args.data1
data18name = args.data2
mcname  = args.mc

can = TCanvas("can", "can", 800, 800)
can.cd()
can.SetTickx()
can.SetTicky()
#can.SetLogy()
#can.SetGrid(1,1)

datafile = TFile(dataname)
data18file = TFile(data18name)
mcfile = TFile(mcname)


eff_jetpt = datafile.Get("eff_CalojetPt40")
eff_jetpt_2018 = data18file.Get("eff_CalojetPt40")
eff_jetpt_mc = mcfile.Get("eff_CalojetPt40")

gra_jetpt = eff_jetpt.CreateGraph()
gra_jetpt_2018 = eff_jetpt_2018.CreateGraph()
gra_jetpt_mc = eff_jetpt_mc.CreateGraph()
gra_jetpt.SetTitle("")
gra_jetpt.SetMarkerColor(kBlack)
gra_jetpt.SetMarkerStyle(ROOT.kFullCircle)
gra_jetpt.SetMarkerSize(0.75)
gra_jetpt_2018.SetMarkerColor(kBlue)
gra_jetpt_2018.SetMarkerStyle(ROOT.kFullCircle)
gra_jetpt_2018.SetMarkerSize(0.75)
gra_jetpt_2018.SetLineColor(kBlue)
gra_jetpt_mc.SetMarkerColor(kRed)
gra_jetpt_mc.SetMarkerStyle(ROOT.kFullCircle)
gra_jetpt_mc.SetMarkerSize(0.75)
gra_jetpt_mc.SetLineColor(kRed)
gra_jetpt.GetXaxis().SetTitle("Offline Calo jet p_{T} [GeV]")
#gra_PromptTrk.GetXaxis().SetRangeUser(-0.5,16.5)
#gra_PromptTrk.GetYaxis().SetRangeUser(0, 1.0)
gra_jetpt.GetYaxis().SetTitle("Online Single Jet Tag Efficiency")
gra_jetpt.Draw("APE")
gra_jetpt_2018.Draw("PE SAME")
gra_jetpt_mc.Draw("PE SAME")
text=ROOT.TLatex(0.65, 0.92, "2022 ")
text.SetNDC()
text.SetTextFont(62)
text.SetTextSize(0.05)
text2=ROOT.TLatex(0.15, 0.92, "CMS #bf{#scale[0.75]{#it{Preliminary}}}")
text2.SetNDC()
text2.SetTextSize(0.05)
text2.SetTextFont(62)
text.Draw("SAME")
text2.Draw("SAME")
leg=ROOT.TLegend(0.5,0.45, 0.85,0.6)
leg.SetLineColor(0)
leg.SetFillColorAlpha(0,0)

leg.AddEntry(gra_jetpt, "Run2022", "pe")
leg.AddEntry(gra_jetpt_2018, "Run2018", "pe")
leg.AddEntry(gra_jetpt_mc, "Run2 QCD MC", "pe")
#leg.AddEntry(gra_PromptTrk_mc, "MC (QCD MultiJet)", "pe")
leg.Draw("SAME")

can.SaveAs("Run3_vs_Run2_CalojetPt40_Eff.png")
can.SaveAs("Run3_vs_Run2_CalojetPt40_Eff.pdf")
can.SaveAs("Run3_vs_Run2_CalojetPt40_Eff.eps")
can.SaveAs("Run3_vs_Run2_CalojetPt40_Eff.C")


can.Update()
eff_PromptTrk = datafile.Get("eff_PromptTrack")
eff_PromptTrk_2018 = data18file.Get("eff_PromptTrack")
eff_PromptTrk_mc = mcfile.Get("eff_PromptTrack")

gra_PromptTrk = eff_PromptTrk.CreateGraph()
gra_PromptTrk_2018 = eff_PromptTrk_2018.CreateGraph()
gra_PromptTrk_mc = eff_PromptTrk_mc.CreateGraph()
gra_PromptTrk.SetTitle("")
gra_PromptTrk.SetMarkerColor(kBlack)
gra_PromptTrk.SetMarkerStyle(ROOT.kFullCircle)
gra_PromptTrk.SetMarkerSize(0.75)
gra_PromptTrk_2018.SetMarkerColor(kBlue)
gra_PromptTrk_2018.SetMarkerStyle(ROOT.kFullCircle)
gra_PromptTrk_2018.SetMarkerSize(0.75)
gra_PromptTrk_2018.SetLineColor(kBlue)
gra_PromptTrk_mc.SetMarkerColor(kRed)
gra_PromptTrk_mc.SetMarkerStyle(ROOT.kFullCircle)
gra_PromptTrk_mc.SetMarkerSize(0.75)
gra_PromptTrk_mc.SetLineColor(kRed)
gra_PromptTrk.GetXaxis().SetTitle("Number of Offline Prompt Tracks")
gra_PromptTrk.GetXaxis().SetRangeUser(-0.5,16.5)
gra_PromptTrk.GetYaxis().SetRangeUser(0, 1.0)
gra_PromptTrk.GetYaxis().SetTitle("Online Single Jet Tag Efficiency")
gra_PromptTrk.Draw("APE")
gra_PromptTrk_2018.Draw("PE SAME")
gra_PromptTrk_mc.Draw("PE SAME")
text=ROOT.TLatex(0.65, 0.92, "2022 ")
text.SetNDC()
text.SetTextFont(62)
text.SetTextSize(0.05)
text2=ROOT.TLatex(0.15, 0.92, "CMS #bf{#scale[0.75]{#it{Preliminary}}}")
text2.SetNDC()
text2.SetTextSize(0.05)
text2.SetTextFont(62)
text.Draw("SAME")
text2.Draw("SAME")
leg=ROOT.TLegend(0.5,0.45, 0.85,0.6)
leg.SetLineColor(0)
leg.SetFillColorAlpha(0,0)

leg.AddEntry(gra_PromptTrk, "Run2022", "pe")
leg.AddEntry(gra_PromptTrk_2018, "Run2018", "pe")
leg.AddEntry(gra_PromptTrk_mc, "Run2 QCD MC", "pe")
leg.Draw("SAME")

can.SaveAs("Run3_vs_Run2_PromptTrack_Eff.png")
can.SaveAs("Run3_vs_Run2_PromptTrack_Eff.pdf")
can.SaveAs("Run3_vs_Run2_PromptTrack_Eff.eps")
can.SaveAs("Run3_vs_Run2_PromptTrack_Eff.C")

can.Update()
eff_DisplacedTrk = datafile.Get("eff_DisplacedTrack")
eff_DisplacedTrk_2018 = data18file.Get("eff_DisplacedTrack")
eff_DisplacedTrk_mc = mcfile.Get("eff_DisplacedTrack")

gra_DisplacedTrk = eff_DisplacedTrk.CreateGraph()
gra_DisplacedTrk_2018 = eff_DisplacedTrk_2018.CreateGraph()
gra_DisplacedTrk_mc = eff_DisplacedTrk_mc.CreateGraph()
gra_DisplacedTrk.SetTitle("")
gra_DisplacedTrk.SetMarkerColor(kBlack)
gra_DisplacedTrk.SetMarkerStyle(ROOT.kFullCircle)
gra_DisplacedTrk.SetMarkerSize(0.75)
gra_DisplacedTrk_2018.SetMarkerColor(kBlue)
gra_DisplacedTrk_2018.SetMarkerStyle(ROOT.kFullCircle)
gra_DisplacedTrk_2018.SetMarkerSize(0.75)
gra_DisplacedTrk_2018.SetLineColor(kBlue)
gra_DisplacedTrk_mc.SetMarkerColor(kRed)
gra_DisplacedTrk_mc.SetMarkerStyle(ROOT.kFullCircle)
gra_DisplacedTrk_mc.SetMarkerSize(0.75)
gra_DisplacedTrk_mc.SetLineColor(kRed)
gra_DisplacedTrk.GetXaxis().SetTitle("Number of Offline Displaced Tracks")
gra_DisplacedTrk.GetXaxis().SetRangeUser(-0.5,12.5)
gra_DisplacedTrk.GetYaxis().SetRangeUser(0, 1.0)
gra_DisplacedTrk.GetYaxis().SetTitle("Online Single Jet Tag Efficiency")
gra_DisplacedTrk.Draw("APE")
gra_DisplacedTrk_2018.Draw("PE SAME")
gra_DisplacedTrk_mc.Draw("PE SAME")
text=ROOT.TLatex(0.65, 0.92, "2022 ")
text.SetNDC()
text.SetTextFont(62)
text.SetTextSize(0.05)
text2=ROOT.TLatex(0.15, 0.92, "CMS #bf{#scale[0.75]{#it{Preliminary}}}")
text2.SetNDC()
text2.SetTextSize(0.05)
text2.SetTextFont(62)
text.Draw("SAME")
text2.Draw("SAME")
leg=ROOT.TLegend(0.5,0.65, 0.85,0.8)
leg.SetLineColor(0)
leg.SetFillColorAlpha(0,0)

leg.AddEntry(gra_DisplacedTrk, "Run2022", "pe")
leg.AddEntry(gra_DisplacedTrk_2018, "Run2018", "pe")
leg.AddEntry(gra_DisplacedTrk_mc, "Run2 QCD MC", "pe")
leg.Draw("SAME")


can.SaveAs("Run3_vs_Run2_DisplacedTrack_Eff.png")
can.SaveAs("Run3_vs_Run2_DisplacedTrack_Eff.pdf")
can.SaveAs("Run3_vs_Run2_DisplacedTrack_Eff.eps")
can.SaveAs("Run3_vs_Run2_DisplacedTrack_Eff.C")
